language: java
jdk:
  - openjdk8

script: ./mvnw clean install
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

notification:
  email: bikash.roshan08@gmail.com
